# This is the base config for the Deal scraper config
# Future might include other websites

# Path to current, up-to-date csv
current_csv_file: deals/scraped/final/deals.csv
# Path to log file
log_file: deals/scraped/final/log.log
# Path to ignore and duplicate list file
user_ignore_list: deals/scraped/final/user_ignore_list.json
dupe_list: deals/scraped/final/dupe_list.json

# isthereanydeals
deal_palace: "https://isthereanydeal.com/"